apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-dotnet60-basic-gdxt
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/rsoaresd_org/spi-demos-zvln-tenant/dotnet-component/devfile-sample-dotnet60-basic-gdxt@sha256:5df772a9fda65d50c5e5c0af077dcdcd10665d2bfed5e8595c703cd061728826
        name: main
        resources: {}
status: {}
