apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-gdxt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-gdxt
    app.kubernetes.io/part-of: dotnet-component
  name: devfile-sample-dotnet60-basic-gdxt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: devfile-sample-dotnet60-basic-gdxt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: devfile-sample-dotnet60-basic-gdxt
    spec:
      containers:
      - image: quay.io/rsoaresd_org/spi-demos-zvln-tenant/dotnet-component/devfile-sample-dotnet60-basic-gdxt@sha256:5df772a9fda65d50c5e5c0af077dcdcd10665d2bfed5e8595c703cd061728826
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
